import numpy
from .Fsm import FSM, State
from .Prompt import Prompt
from dataclasses import dataclass
from llm_sdk import Small_LLM_Model
from typing import Dict, List, Any


@dataclass
class Constrained:
    
    # this class will guide the llm to generate valid tokens
    prompt: str
    functions: Dict
    _model: Small_LLM_Model = Small_LLM_Model()


    def get_valid_token(self, allowed: str, logits) -> int:
        
        # logits are an embedded array 
        logits = numpy.array(logits)
        
        # encode method from the llm takes a string and return a tensor of ids 
        # ids are the position of the tokens in the llm vocabulary
        allowed: List = self._model.encode(allowed).tolist()[0]
        
        # set all invalid logits to -inf 
        # and make only the valid one integer
        masked_logits = numpy.full_like(logits, -numpy.inf)
        
        # replace the valid tokens with there id
        masked_logits[allowed] = logits[allowed]
        
        return numpy.argmax(masked_logits)
    
    def get_valid_fun_name(self):
        pass
    
    def get_valid_params(self):
        pass
    
    def add_prompt(self):
        pass

    @property
    def constrained_decoding(self) -> List:

        # take the input from the user and add it to the prompt
        updated_prompt: str = Prompt(self.prompt, self.functions).update_prompt
        
        # ids are a tensor of places of tokens in llm vocab converted to list
        ids_obj: List[int] = self._model.encode(updated_prompt).tolist()[0]
        
        # start of the json object for one prompt
        state_obj: State = State.START_OBJ
        obj: List[str, Any] = []

        while state_obj != State.DONE:
            
            # check the state of generated tokens
            allowed_token_json: str = FSM.allowed_tokens(state_obj)
            
            # check if the next token will generated by the llm or by the state
            if allowed_token_json is None:
                
                # logits are an array of float numbers (embedded matrix of the llm vocab)
                # ids are converted to vectors
                logits = self._model.get_logits_from_input_ids(ids_obj)
                valid_logit: List[int] = [int(numpy.argmax(ids_obj))]
        
            else:
                # encode the token defined by the state and add it to ids
                valid_logit: List[int] = self._model.encode(allowed_token_json).tolist()[0]
            
            # append the valid logit id to the list of generated tokens ids
            ids_obj.extend(valid_logit)

            state_obj = FSM.next_state_for_one_prompt(state_obj)

            if obj != None:
                print(obj)
