import numpy
from .Fsm import FSM, State
from .Prompt import Prompt
from dataclasses import dataclass
from llm_sdk import Small_LLM_Model
from typing import Dict, List, Any
from .functions import Functions

@dataclass
class Constrained:

    # this class will guide the llm to generate valid tokens
    prompt: str
    functions_data: Dict
    _model: Small_LLM_Model = Small_LLM_Model()

    def get_valid_function(self, allowed: List[List[int]], ids_obj:List[int]) -> List[int]:

        generated: List[int] = []

        while True:

            # logits are an embedded array
            logits: List[float] = self._model.get_logits_from_input_ids(ids_obj)
            logits: List[int] = numpy.array(logits)
            next_token: List[int] = []

            for function in allowed:

                if function[: len(generated)] == generated:

                    if len(generated) < len(function):

                        next_token.append(function[len(generated)])

                # set all invalid logits to -inf
                # and make only the valid one integer
            masked_logits = numpy.full_like(logits, -numpy.inf)

            # replace the valid ids
            masked_logits[next_token] = logits[next_token]

            # take the max valid logit
            valid_logit = numpy.argmax(masked_logits)

            # append it to the list of generated ids of the token
            generated.append(valid_logit)
            ids_obj.append(valid_logit)

            if generated in allowed:
                break

        return generated

        # get the list of the allowed function names
    @property
    def get_valid_fun_name(self) -> List[str]:
        fun_names = [
            self._model.encode(Functions(self.functions_data[i]).name).tolist()[0]
            for i in range(len(self.functions_data))
            ]
        return fun_names

        # get the list of the allowed parameters for each function
    @property
    def get_valid_params(self):
        fun_params = [
            Functions(self.functions_data[i]).parameters
            for i in range(len(self.functions_data))
        ]
        return fun_params

        # get the list of the description of each function
    @property
    def get_description(self):
        fun_desc = [
            self._model.encode(Functions(self.functions_data[i]).description).tolist()[0]
            for i in range(len(self.functions_data))
        ]
        return fun_desc

    @property
    def constrained_decoding(self) -> List:

        # take the input from the user and add it to the prompt
        updated_prompt: str = Prompt(self.prompt, self.functions_data).update_prompt

        # ids are a tensor of places of tokens in llm vocab converted to list
        # encode method from the llm takes a string and return a tensor of ids
        # ids are the position of the tokens in the llm vocabulary
        ids_obj: List[int] = self._model.encode(updated_prompt).tolist()[0]
        prompt_len = len(ids_obj)

        # start of the json object for one prompt
        state_obj: State = State.START_OBJ
        obj: List[str, Any] = []

        while state_obj != State.DONE:

            # check the state of generated tokens
            allowed_token_json: str = FSM.allowed_tokens(state_obj)

            # check if the next token will generated by the llm or by the state
            # logits are an array of float numbers (embedded matrix of the llm vocab)
            # ids are converted to vectors
            if allowed_token_json == '0':
                valid_logit: List[int] = self._model.encode(
                    '"' + self.prompt + '"'
                ).tolist()[0]
                ids_obj.extend(valid_logit)

            elif allowed_token_json == '1':
                valid_logit = self.get_valid_function(self.get_valid_fun_name, ids_obj)
            # elif allowed_token_json == '2':

            else:
                # encode the token defined by the state and add it to ids
                valid_logit: List[int] = self._model.encode(allowed_token_json).tolist()[0]
                ids_obj.extend(valid_logit)
                # append the valid logit id to the list of generated tokens ids

            state_obj = FSM.next_state_for_one_prompt(state_obj)
        ids_obj = ids_obj[prompt_len:]
        return self._model.decode(ids_obj)
